#!/bin/bash

#
# This script is for automating installation of programs and repositories for Fedora and
# speeding up the uptime on a fresh install.
# Check comments for optional installs.
#


echo 'Beginning installscript............'
echo 'Enabling repositories......'
#Enable RPM Fusion repositories
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

#Enable flatpak repository
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echo 'Downloading programs......'
#Download brave browser
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
sudo dnf install -y brave-browser

#Download Visual Studio Code
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf check-update
sudo dnf install -y code


#Download VIm
sudo dnf install -y vim

#Download BitWarden
flatpak install -y flathub com.bitwarden.desktop

#Download Steam
flatpak install -y flathub com.valvesoftware.Steam

#Download Inkscape
flatpak install -y flathub org.inkscape.Inkscape

#Download Discord
flatpak install -y flathub com.discordapp.Discord

#Download VLC
flatpak install -y flathub org.videolan.VLC

#Download Spotify
flatpak install -y flathub com.spotify.Client


#Download Yarn
curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
sudo dnf install -y yarn

#Download NVM for node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

#Download latest version of node
nvm install -y node

#Download Thunderbird
sudo dnf install -y thunderbird thunderbird-enigmail

#Install Clang/gcc-g++
sudo dnf install -y clang gcc-c++

#Download Docker-ce and Docker-compose
#sudo dnf config-manager \
#    --add-repo \
#    https://download.docker.com/linux/fedora/docker-ce.repo
#sudo dnf install docker-ce docker-ce-cli containerd.io
#sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#sudo chmod +x /usr/local/bin/docker-compose
#echo 'update CGroups if running fedora 31'

#Install TLP
#sudo dnf install tlp tlp-rdw
#sudo tlp start

#Creating home folders
echo 'creating directories......'
mkdir ~/Documents/programming
#mkdir ~/bin
mkdir ~/Documents/Professional Documents/

#Set gtk-theme to dark
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

#Update packages
echo 'Updating system'
sudo dnf -y update

echo 'Configuring git credentials'
echo 'enter email'
read email
git config --global user.email "$email"
git config --global user.name "McQuade, Dillon"

#Reboot system
echo 'Dont forget to install zsh/oh-my-zsh, slack, virtualbox, configure git'
echo 'And JetBrains ToolBox!'
read 'Press enter to reboot'

reboot

